language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - yarn build
deploy:
  provider: heroku
  api_key:
    secure: <your-api-key>
  app: cd-showcase
  on:
    branch: master
