language: node_js
node_js:
- 14.3.0
deploy:
  provider: heroku
  api_key:
    secure: oIPPOZcxtS150V3UVn3s+3z45HZXahOV/+A9FrMcdaDJe4LI60m4VdM+DT00CfipJBYaf9UBKCGJKMLUhku6J9z0b6F4JlTKISMYLxD+0w3UhM7drAJJDxEOACkSwwKrxYqaGNL/nWTG1joHY4ZulOSaTgeGm7ql4cKJhnhA9WtRGqQ9uqbpBVuzt7OXeiUy1XuT6KrALjReEA2AxZOrstNzm7vH3wvpqMpGm1vQJefMLj1c6TQx3s8umAPQ34FORkunYJcTKnHZkzgTX28kobUsrrmIUrpZhkJvi8YChDVinL6MKsQy3sb51X21Hpjilg+tMLgKElnge9e9ODJrDBVqp5JunWT1qSwysAUkH6pdTnvrdyoAS2RkyiaB37tJUs3fszqFmPo8qjmTgvmPbBJ/NwpiwRrogcLnFI9JK+MQyCf+gdOsSi9Nt105ljJcvj9cwTWMgJu9zdVQV6mPS7PkSTffugxzB6ILlXPepqegeswQ5JXQYOmoVJxqVNhJi56OC8BRR4QLITz2B6X7+lSDgNx1pb0NCJiSMfO+iQbohbPdyA1DT6XmBEqPcaR15lSAKo1I1QUHiFNnms6VOW9Kr0Gydrn6uLzQqLnNEdtlN3fY0Nt4HvnkFGy1aHolXQp5R9TG1ILZEwpcDtd0ZgSMj6eEdVxeWOIg7H4nD1k=
  app: flixi
  on:
    branch: master
