language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - yarn build
deploy:
  provider: heroku
  api_key:
    secure: gYlJEDeW89E6Yagb5XUHljmKVeqafHhBD8zOBkie0zI5D2RB7bw1I1NX9Klbb18fu63hLO+dJD94NmC2owryLyizHak4lyCzzWYOXNsfH3dFfMAnGSslXFg+O90Cc02W6v5WkdPzEQNzVbNSooXyEZKsEwDSLIYf0Aj5uDfi7nn8HyJ69AcHp5z3gWRvp7Q/rUuPXrTq7EjiZv9zUK6THzHwXzPh1ZyqxI/L5pJOxdpOO6Vj7KSp31GiEBiVoOUpeaHskfqpCpj58IC0sAJU4rNtdfim6iF2kofLQ7lQ9zmNGgJA2pbMswrGK43lMIh1kb/p7ru6sHXfJmxP2oZAu8kC5GvSlRXhE1yseLqhmp+Io7TH23eOFN3lOkJCtIOKqc96Gbb2Q8lgr+65+CRQ6Fpmw438iohrX4RWhEgngn4M+1hTNcZg7wMJotnnTtxwEUYdd8qLW7PxJHSp4PfsaSOK/i3duC7fwj3Ik55RhYIJXbag/R640TJKbt/lBMLgLdiciT8Lh6OFb8jcw3/wdhGKMtp0afxCtbdbfPPUmxPMIlGg2Xv93J9uSOyFzsbYZ48aoghw0cY9Oyh2SGVBvgpXBnhGjYjP3mzUoip/YQM5DURkBrkRMuTE8prJI3YSLqIPL6ozdtIz+IorSfQl37RVphDkFs3JHZnTux7OYdE=
  app: cd-showcase
  on:
    branch: master
